eshop/eshop.MVC/ViewComponents/CategoryMenuViewComponent.cs
using eshop.Application;
using Microsoft.AspNetCore.Mvc;

namespace eshop.MVC.ViewComponents
{
    public class CategoryMenuViewComponent(ICategoryService categoryService) : ViewComponent
    {
        
        public IViewComponentResult Invoke()
        {
            var categories = categoryService.GetCategories();
            return View(categories);
        }
    }
}

eshop/eshop.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - eshop.MVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/eshop.MVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">eshop.MVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                   
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Basket" asp-action="Index">Sepet</a>
                        </li>
                        @if (User.IsInRole("Admin") || User.IsInRole("Editor"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Products" asp-action="Index">Ürün İşlemleri</a>
                            </li>
                        }
                        <li class="nav-item">
                            @if (!User.Identity.IsAuthenticated)
                            {
                                <a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="Login">Giriş Yap</a>
                            }
                            else
                            {
                                <a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="Logout"> @User.Identity.Name (Çıkış Yap)</a>

                            }
                        </li>
                      
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <div class="row">
            <div class="col-2">@await Component.InvokeAsync("CategoryMenu")</div>
            <div class="col-10">
                <main role="main" class="pb-3">
                    @RenderBody()
                </main>
            </div>

        </div>
      
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - eshop.MVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

eshop/eshop.MVC/Views/Shared/_ProductCard.cshtml
@model ProductDisplayResponse
<div class="card">
    <img src="@Model.ImageUrl" class="img-fluid" />
    <div class="card-body">

        <h3 class="card-title">@Model.Name</h3>
        <p class="card-text">@Model.Description</p>
        <p class="card-text">@Model.Price</p>

        <button class="btn btn-success basket" data-id="@Model.Id"> Sepete Ekle</button>

    </div>
</div>